package az.fintech.unitech.enums;

public enum ExceptionMessageEnum {
    PIN_OR_PASSWORD_WRONG_PLEASE_CHECK_AND_RETRY,
    PIN_ALREADY_REGISTERED,
    TRANSFER_DOES_NOT_ALLOWED_BETWEEN_SAME_ACCOUNT,
    TRANSFER_DOES_NOT_ALLOWED_TO_SEND_CLOSED_ACCOUNT,
    TRANSFER_DOES_NOT_ALLOWED_TO_SEND_NON_EXISTING_ACCOUNT,
    THERE_IS_NOT_ENOUGH_MONEY_YOUR_ACCOUNT,
    UN_SUPPORTED_CURRENCY_NAME
}
